"""ClearLens data contract. FROZEN — agreed at kickoff, changed only by the team lead.

Everything in the pipeline passes these shapes. The UI, the agents and the duty engine are
written against this file, so the front end can be built on mock data before any agent works.

Rules that matter:
  * `verified` and `confirmed_by_human` are set by code or by a person, never by a model.
  * Money is Decimal, never float. Rupees do not survive floating point.
"""
from dataclasses import asdict, dataclass, field
from decimal import Decimal
from typing import Any, List, Optional

# ---------------------------------------------------------------- enumerations
DOC_TYPES = ["invoice", "packing_list", "bill_of_lading"]

SEVERITIES = ["blocking", "advisory"]

IMPORTER_STATUSES = [
    "commercial_filer", "commercial_non_filer",
    "industrial_filer", "industrial_non_filer",
]

INCOTERMS = ["EXW", "FOB", "CFR", "CIF", "CPT", "CIP", "DAP", "DDP", "FCA", "FAS"]


def D(value: Any, default: str = "0") -> Decimal:
    """Anything -> Decimal, tolerantly. '1,250.50' and 'USD 1250.5' both work."""
    if isinstance(value, Decimal):
        return value
    if value is None or value == "":
        return Decimal(default)
    s = str(value).replace(",", "").strip()
    keep = "".join(ch for ch in s if ch.isdigit() or ch in ".-")
    try:
        return Decimal(keep or default)
    except Exception:  # noqa: BLE001 - never crash the pipeline on a model's bad number
        return Decimal(default)


# ---------------------------------------------------------------- documents
@dataclass
class LineItem:
    """One product line, as read from ONE document. The same goods appear up to three times."""
    source_doc: str                      # invoice | packing_list | bill_of_lading
    line_no: int
    description: str
    quantity: Decimal = Decimal("0")
    unit: str = ""
    unit_price: Decimal = Decimal("0")
    currency: str = ""
    value: Decimal = Decimal("0")
    net_weight_kg: Decimal = Decimal("0")
    gross_weight_kg: Decimal = Decimal("0")
    origin: str = ""
    incoterm: str = ""
    page: int = 1
    quote: str = ""                      # verbatim line from the document
    verified: bool = False               # set by the citation checker, never by the model
    verify_note: str = ""

    def to_dict(self) -> dict:
        return {k: (str(v) if isinstance(v, Decimal) else v) for k, v in asdict(self).items()}


@dataclass
class Discrepancy:
    """One field where the three documents disagree."""
    field_name: str
    values: dict                         # {"invoice": "500", "packing_list": "496", ...}
    severity: str = "blocking"           # blocking | advisory
    note: str = ""
    resolved_value: Optional[str] = None # filled at human gate 1

    def to_dict(self) -> dict:
        return asdict(self)


# ---------------------------------------------------------------- classification
@dataclass
class Classification:
    """A proposed tariff code for one reconciled line. Advisory until a human confirms it."""
    line_no: int
    pct_code: str = ""                   # eight digits, e.g. "0703.2000"
    heading_text: str = ""               # VERBATIM from the tariff, never paraphrased
    reasoning: str = ""
    confidence: str = "low"              # low | medium | high
    alternatives: List[dict] = field(default_factory=list)   # [{pct_code, heading_text, why}]
    confirmed_by_human: bool = False

    def to_dict(self) -> dict:
        return asdict(self)


# ---------------------------------------------------------------- money
@dataclass
class DutyResult:
    """Output of the duty engine. Every field is computed; none is generated by a model."""
    pct_code: str
    cif_pkr: Decimal
    cd_rate: Decimal
    acd_rate: Decimal
    rd_rate: Decimal
    st_rate: Decimal
    wht_rate: Decimal
    cd_amount: Decimal
    acd_amount: Decimal
    rd_amount: Decimal
    duty_paid_value: Decimal
    sales_tax: Decimal
    wht: Decimal
    total_taxes: Decimal
    landed_cost: Decimal
    effective_rate_pct: Decimal          # total_taxes / cif, for the headline number

    def to_dict(self) -> dict:
        return {k: str(v) for k, v in asdict(self).items()}


@dataclass
class Consignment:
    """Everything the UI needs for one import. This is the object that moves through the app."""
    reference: str = ""
    importer_status: str = "commercial_filer"
    fx_rate: Decimal = Decimal("1")      # foreign currency -> PKR
    freight: Decimal = Decimal("0")
    insurance: Decimal = Decimal("0")
    lines: List[LineItem] = field(default_factory=list)
    discrepancies: List[Discrepancy] = field(default_factory=list)
    classifications: List[Classification] = field(default_factory=list)
    duties: List[DutyResult] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "reference": self.reference,
            "importer_status": self.importer_status,
            "fx_rate": str(self.fx_rate),
            "freight": str(self.freight),
            "insurance": str(self.insurance),
            "lines": [l.to_dict() for l in self.lines],
            "discrepancies": [d.to_dict() for d in self.discrepancies],
            "classifications": [c.to_dict() for c in self.classifications],
            "duties": [d.to_dict() for d in self.duties],
        }


# ---------------------------------------------------------------- model output -> our shapes
def coerce_line_item(raw: dict, source_doc: str, idx: int) -> Optional[LineItem]:
    """Turn one raw object from an extraction agent into a LineItem, or None if unusable.

    The model is not trusted: unknown fields are dropped and bad numbers become zero rather
    than crashing the pipeline halfway through a demo.
    """
    if not isinstance(raw, dict):
        return None
    description = str(raw.get("description") or "").strip()
    if not description:
        return None
    doc = source_doc if source_doc in DOC_TYPES else "invoice"
    try:
        page = max(1, int(float(raw.get("page", 1))))
    except (TypeError, ValueError):
        page = 1
    return LineItem(
        source_doc=doc,
        line_no=int(raw.get("line_no") or idx),
        description=description[:300],
        quantity=D(raw.get("quantity")),
        unit=str(raw.get("unit") or "")[:30],
        unit_price=D(raw.get("unit_price")),
        currency=str(raw.get("currency") or "")[:8].upper(),
        value=D(raw.get("value")),
        net_weight_kg=D(raw.get("net_weight_kg")),
        gross_weight_kg=D(raw.get("gross_weight_kg")),
        origin=str(raw.get("origin") or "")[:40],
        incoterm=(str(raw.get("incoterm") or "").upper()[:4] if str(raw.get("incoterm") or "").upper()[:4] in INCOTERMS else ""),
        page=page,
        quote=str(raw.get("quote") or "")[:800],
    )


def coerce_classification(raw: dict, line_no: int) -> Classification:
    conf = str(raw.get("confidence") or "low").lower()
    alts = raw.get("alternatives") or []
    return Classification(
        line_no=line_no,
        pct_code=str(raw.get("pct_code") or "").strip()[:12],
        heading_text=str(raw.get("heading_text") or "").strip()[:500],
        reasoning=str(raw.get("reasoning") or "").strip()[:800],
        confidence=conf if conf in ("low", "medium", "high") else "low",
        alternatives=[a for a in alts if isinstance(a, dict)][:3],
    )
